# Generated by Django 3.1.5 on 2021-02-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_bid_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuctionListing',
        ),
    ]
