# Generated by Django 3.1.5 on 2021-02-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_delete_auctionlisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=150)),
                ('startbid', models.IntegerField()),
                ('url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=16)),
            ],
        ),
    ]
