# Generated by Django 3.1.5 on 2021-02-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210206_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
