# Generated by Django 3.1.5 on 2021-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
