# Generated by Django 3.1.5 on 2021-02-07 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210207_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='startbid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidia', to='auctions.bid'),
        ),
    ]
