# Generated by Django 3.1.5 on 2021-02-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210207_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
