# Generated by Django 3.1.5 on 2021-02-08 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210208_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentia', to='auctions.comment'),
        ),
    ]
