# Generated by Django 3.1.5 on 2021-02-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210208_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='comment',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='commentia', to='auctions.Comment'),
        ),
    ]
